services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres_db
    image: volha564/library-db:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: musiclibrarydb
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgers_logs:/var/log/postgresql
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: volha564/library-app:latest
    container_name: node_app
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:123321@postgres_db:5432/musiclibrarydb?schema=public
    networks:
      - app-network
    restart: always
    entrypoint: ['sh', '-c', 'npx prisma migrate deploy && npm run start']

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  postgers_logs:
